baseURL = "https://chingyuuuuu.github.io/"
languageCode = "zh-tw"
title = "Cheese's Blog"
theme = "PaperMod"

[taxonomies] # 文章分類系統
  category = "categories"
  tag = "tags"
  archive = "archives"

[params]
  defaultTheme = "light"  
  ShowToc = true  # 顯示文章目錄
  ShowReadingTime = true  # 顯示閱讀時間
  ShowBreadCrumbs = true  # 顯示路徑
  sectionPagesMenu = "main"# 讓所有 Section 自動加入 `menu.main`
  mainSections = ["posts"] 
  author = "Ching"
  subtitle = "分享人生"
  keywords = ["Blog","技術","生活"]
  favicon = "/favicon.ico" 
  customCSS = ["css/custom.css?v=20250303"]


[params.profile]
  enabled = true  # ✅ 開啟個人簡介
  name = "Ching"
  bio = "Yolo！"
  avatarURL = "/img/avatar.png"  # ✅ 請放入你的頭像圖片
  location = "Taiwan"
  github = "https://github.com/chingyuuuuu"
  instagram = "https://www.instagram.com/your_instagram/"
  youtube = "https://www.youtube.com/@kplan-e6r"
  website = "https://chingservice.wixsite.com/ching"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  [[menu.main]]
    identifier = "archives"
    name = "所有文章"
    url = "/archives/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 3