baseURL = "https://example.org/"
languageCode = "zh-tw"
title = "Cheese's Blog"
theme = "hugo-coder"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[params]
  ShowToc = true  # 顯示文章目錄
  ShowReadingTime = true  # 顯示閱讀時間
  ShowBreadCrumbs = true  # 顯示路徑
  sectionPagesMenu = "main"
  mainSections = ["posts"]
  enableProfile = false  # 啟用個人簡介

[params.profile]
  enabled = true  # 開啟個人簡介
  name = "Ching"
  bio = "Follow your heart"
  avatarURL = "/img/avatar.png"  
  location = "Taiwan"
  website = "https://chingservice.wixsite.com/ching"
  github = "https://github.com/chingyuuuuu"
  youtube = "https://www.youtube.com/@kplan-e6r"

[[params.social]]
  name = "website"
  url = "https://chingservice.wixsite.com/ching"
  weight = 1

[[params.social]]
  name = "github"
  url = "https://github.com/chingyuuuuu"
  weight = 2

[[params.social]]
  name = "youtube"
  url = "https://www.youtube.com/@kplan-e6r"
  weight = 3


[menu]
  [[menu.main]]
    identifier = "archives"
    name = "所有文章"
    url = "/archives/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 3
